### PR TITLE
Fix author list

### PR DESCRIPTION
**Pull request by Bisaloo**
see https://github.com/r-universe-org/help/issues/152#issuecomment-1125680609

### CODE REVIEW

**Comment by jeroen** [comment]
This is still incorrect, the `c()` needs to wrap both persons.

**Comment by Bisaloo** [comment]
> This is still incorrect, the c() needs to wrap both persons.

It does. The diff is just confusing because I'm fixing two mistakes in this PR (missing `c()` and missing closing parenthesis).

**Comment by jeroen** [comment]
Oh right haha

**Comment by seabbs** [comment]
Thanks for this @Bisaloo. Sadly catching up on my notifications in a very illogical order and so fixed this in https://github.com/epiforecasts/forecast.vocs/commit/a190db3a8f239ec716ef01466ce8178144d18269

**Pull request closed without merging**
